saecki/crates.nvim

lua/crates.lua, lua/crates/config.lua, lua/crates/diagnostic.lua, lua/crates/popup.lua, lua/crates/toml.lua, teal/crates.tl, teal/crates/config.tl, teal/crates/diagnostic.tl, teal/crates/popup.tl, teal/crates/toml.tl
=> Differentiate target specific, dev, build, and normal dependencies

lua/crates/config.lua, lua/crates/diagnostic.lua, teal/crates/config.tl, teal/crates/diagnostic.tl
=> fix(diagnostic): add option to disable invalid feature diagnostics

lua/crates/toml.lua, teal/crates/toml.tl
=> fix(toml): parse package rename declarations

README.md, doc/crates.txt, lua/crates.lua, lua/crates/api.lua, lua/crates/config.lua, lua/crates/popup.lua, lua/crates/state.lua, plugin/crates.vim, scripts/README.md.in, scripts/crates.txt.in, teal/crates.tl, teal/crates/api.tl, teal/crates/config.tl, teal/crates/diagnostic.tl, teal/crates/popup.tl, teal/crates/state.tl, teal/crates/toml.tl, tlconfig.lua
This adds a dependencies popup which allows navigating the crate dependency hierarchy.
=> Dependencies popup

lua/crates/semver.lua, teal/crates/semver.tl
=> fix: parse bare wildcards

README.md, scripts/README.md.in
=> docs: update plain text config example

README.md, doc/crates.txt, lua/crates/api.lua, lua/crates/config.lua, teal/crates/api.tl, teal/crates/config.tl
This makes the curl arguments configurable and defaults to `1` retry. Closes #41
=> feat: add curl_args config option

README.md, doc/crates.txt, lua/crates/async.lua, lua/crates/config.lua, lua/crates/init.lua, teal/crates/async.tl, teal/crates/config.tl, teal/crates/init.tl, types/vim.d.tl
This reduces stutter and typing lag for larger toml files
=> feat: throttle auto update

README.md, doc/crates.txt, lua/crates/config.lua, lua/crates/popup/versions.lua, teal/crates/config.tl, teal/crates/popup/versions.tl
=> feat: add popup.hide_on_select config option

README.md, scripts/README.md.in
=> docs: add video

README.md, doc/crates.txt, lua/crates/config.lua, lua/crates/health.lua, lua/crates/util.lua, teal/crates/config.tl, teal/crates/health.tl, teal/crates/util.tl
=> feat: make programs to open URL's configurable (open_programs)

README.md, doc/crates.txt, lua/crates/actions.lua, lua/crates/edit.lua, lua/crates/init.lua, lua/crates/toml.lua, scripts/README.md.in, scripts/crates.txt.in, teal/crates/actions.tl, teal/crates/api.tl, teal/crates/diagnostic.tl, teal/crates/edit.tl, teal/crates/init.tl, teal/crates/toml.tl
Closes #55, by adding two code refactoring actions.
- expand_plain_crate_to_inline_table
- extract_crate_into_table
=> feat: add refactoring actions

lua/crates/core.lua, lua/crates/init.lua, lua/crates/src/common.lua, teal/crates/core.tl, teal/crates/init.tl, teal/crates/src/common.tl
=> fix: completion menu not triggering automatically

README.md, scripts/README.md.in
=> docs: fix readme lazy example

README.md, doc/crates.txt, lua/crates/config.lua, lua/crates/diagnostic.lua, teal/crates/config.tl, teal/crates/diagnostic.tl
This option allows disabling the update_available warning diagnostic.
=> feat: add enable_update_available_warning config

lua/crates/popup/common.lua, lua/crates/popup/features.lua, lua/crates/popup/init.lua, lua/crates/util.lua, teal/crates/popup/common.tl, teal/crates/popup/features.tl, teal/crates/popup/init.tl, teal/crates/util.tl
=> perf: significantly speed up features popup on large feature sets

lua/crates/api.lua, teal/crates/api.tl
=> fix: fetch_deps enqueueing callback multiple times

README.md, docgen/templates/README.md.in, lua/crates/api.lua, lua/crates/health.lua
Remove the plenary dependency by implementing a simple job mechanism based on `uv.spawn`
=> refactor: replace plenary job

.github/workflows/CI.yml, Makefile, doc/crates.txt, docgen/gen_doc.lua, docgen/templates/crates.txt.in, docgen/wiki/Documentation-unstable.md, lua/crates/config/init.lua, lua/crates/config/types.lua, lua/crates/init.lua, scripts/gen_types.lua
Generate the `Config` and `crates.UserConfig` type from the configuration schema.
=> feat: expose crates.UserConfig type

lua/crates/diagnostic.lua
Thanks for the very useful plugin!
=> fix: `workspace.dependencies` is warned

lua/crates/src/common.lua
=> fix: don't suggest "default" in feature list completion

.github/ISSUE_TEMPLATE/bug_report.yaml
Also update issue template as mentioned in #125
=> chore: update github bug report template

lua/crates/completion/common.lua
=> fix: completion freezing

lua/crates/completion/common.lua, lua/crates/edit.lua, lua/crates/toml.lua, lua/crates/types.lua
- update existing version
- more completion details
=> feat(completion): improve crate completion

lua/crates/actions.lua, lua/crates/command.lua, lua/crates/edit.lua, lua/crates/init.lua
Implement action to switch from a version to git source
=> `Use git source` command

doc/crates.txt, docgen/wiki/Documentation-unstable.md, lua/crates/config/init.lua, lua/crates/config/types.lua, lua/crates/health.lua, lua/crates/util.lua
=> feat!: remove `open_programs` and use `vim.ui.open()`

lua/crates/toml.lua
=> fix: parse sections containing whitespace

lua/crates/ui.lua
=> fix(ui): set diagnostic bufnr

lua/crates/health.lua
=> fix(health): check if setup has been called

lua/crates/completion/common.lua, lua/crates/types.lua
This replaces the whole version, instead of just minor or patch number (See #152)
=> fix(completion): set edit range completing crate versions
