saecki/crates.nvim

README.md

I think most people want to use the Github URL instead of your local folder.

Fix plugin URL in README example

---

lua/crates/popup.lua
teal/crates/popup.tl
types/types.d.tl

table.unpack() is not work in neovim LuaJIT 2.1.0-beta3
`toggle_feature` doesn't work properly because of table.unpack()

Use unpack() instead of table.unpack()

---

README.md
scripts/README.md.in
scripts/crates.txt.in

- Change `autocmd` command for lazy loading cmp source to a lua function equivalent 
- Change `nvim_set_keymap` to the newer `vim.keymap.set` which can map keys to lua functions directly
- Add `vim.keymap.set` equivalent for `noremap` commands

docs: update readme and vimdoc

---

lua/crates/toml.lua
teal/crates/toml.tl

fix: don't show duplicate crate entry error for renamed crate

---

lua/crates/toml.lua
teal/crates/toml.tl

[Workspace inheritance](https://github.com/rust-lang/cargo/issues/8415) was recently [stabilized](https://github.com/rust-lang/cargo/pull/10859) and will be included in the `1.64` release on [Sep 22 2022](https://forge.rust-lang.org/#current-release-versions).
This PR simply treats the `[workspace.dependencies]` table as a default table, since it previously were treated as an invalid dependency section. Per the [RFC](https://rust-lang.github.io/rfcs/2906-cargo-workspace-deduplicate.html#updates-to-workspace), only regular `dependencies` are supported in the `[workspace]` table.

feat: support workspace dependencies

---

README.md
doc/crates.txt
lua/crates/init.lua
lua/crates/popup/dependencies.lua
lua/crates/popup/init.lua
scripts/README.md.in
teal/crates/init.tl
teal/crates/popup/init.tl

This function simply allows the user to ask `crates.nvim` whether it has a popup to show at the current position. I also updated the [example `show_documentation`](https://github.com/Saecki/crates.nvim#show-appropriate-documentation-in-cargotoml) function to include this check to allow the LSP to show hover information in other areas of a `Cargo.toml` file.

Add `popup_available` function

---

lua/crates/actions.lua
lua/crates/config.lua
lua/crates/core.lua
lua/crates/diagnostic.lua
lua/crates/edit.lua
lua/crates/toml.lua
lua/crates/types.lua
teal/crates/actions.tl
teal/crates/config.tl
teal/crates/core.tl
teal/crates/diagnostic.tl
teal/crates/edit.tl
teal/crates/toml.tl
teal/crates/types.tl

closes #44 by adding a diagnostic for mismatched crate name casing. Also adds an action to rename the crate to the correct one.

fix: add diagnostic for invalid crate name casing

---

lua/crates/toml.lua
teal/crates/toml.tl

minimal example of the bug:
```toml
[dependencies]
serde = { version = "*", default-features = false}
```
without this, `Invalid boolean value` is shown

fix(toml): inline tables without extra spaces at the end

---

lua/crates/popup/common.lua
teal/crates/popup/common.tl

Fixes #53 by choosing a more uncommon name for the popup buffer.

fix: popup showing netrw a dir named "crates" exists

---

lua/crates/init.lua
teal/crates/init.tl

Fix the scenario when lazy loading with `BufRead Cargo.toml` event, `M.update()` was not called immediately.

fix: trigger initial update when lazy loading

---

README.md
doc/crates.txt
lua/crates/api.lua
lua/crates/config.lua
teal/crates/api.tl
teal/crates/config.tl

Fixes #62 by introducing the `max_parallel_requests` config option (default `80`).

fix: limit number of parallel requests using a queue

---

README.md
doc/crates.txt
lua/crates/config.lua
lua/crates/init.lua
scripts/gen_doc.lua
teal/crates/config.tl
teal/crates/init.tl

Useful for adding keymaps when `Cargo.toml` is opened.
```lua
require("crates").setup({
on_attach = function(bufnr)
require("config.utils").set_keymaps("n", {
{
"<Leader>ac",
vim.lsp.buf.code_action,
"[lsp] code action",
mode = { "n", "v" },
},
{
"K",
function()
if crates.popup_available() then
crates.show_popup()
else
vim.lsp.buf.hover()
end
end,
"[lsp] hover",
},
}, { buffer = bufnr })
end,
null_ls = {
enabled = true,
name = "crates.nvim",
},
})
```

feat(config): add 'on_attach'

---

CONTRIBUTING.md
lua/crates/health.lua
teal/crates/health.tl
types/health.d.tl
types/vim.d.tl

closes #70
health api was changed in https://github.com/neovim/neovim/pull/22927
tested on both Nvim nightly and v0.9.1
never worked with teal before so hope it's not too bad. not sure what I did with the types are good.

fix: avoid checkhealth deprecation warnings

---

lua/crates/diagnostic.lua
lua/crates/popup/features.lua
lua/crates/popup/versions.lua
lua/crates/toml.lua
lua/crates/types.lua
teal/crates/diagnostic.tl
teal/crates/popup/features.tl
teal/crates/popup/versions.tl
teal/crates/toml.tl
teal/crates/types.tl

Fixes #63. Don't show this error since we can't resolve `workspace` dependencies.

fix: don't show errors for workspace dependencies

---

lua/crates/core.lua
lua/crates/diagnostic.lua
lua/crates/toml.lua
lua/crates/types.lua
lua/crates/ui.lua
teal/crates/core.tl
teal/crates/diagnostic.tl
teal/crates/toml.tl
teal/crates/types.tl
teal/crates/ui.tl

Fixes #75. Since we currently can't resolve workspace, path, or git depencencies there is no guarantee that any crate with the same name we would fetch from crates.io is in any way related to local dependency.

fix: don't show possibly misleading info or diagnostics for local depencencies

---

lua/crates/src/common.lua
teal/crates/src/common.tl

Fixes #79 
Schedule the completion call to the next event loop cycle to make sure update has been called even if the TextChanged autocmd of nvim-cmp has been called first.

fix: completion triggered before update has started

---

lua/crates/core.lua
teal/crates/core.tl

This is a temporary fix for #51. I might at some point try to implement proper support for custom registries, but for now this fix just disables the errors for dependencies that are from custom registries, avoiding the primary problem it causes.

fix: disable errors when dep is from custom registry

---

lua/crates/edit.lua
teal/crates/edit.tl

cargo renamed the field to use hyphen instead of underscore some versions ago, giving this error on some commands (like `cargo remove`)
```
error: Use of `default_features` in `axum` is unsupported, please switch to `default-features`
```

chore: rename default_features to default-features

---

lua/crates/api.lua
lua/crates/core.lua
lua/crates/diagnostic.lua
lua/crates/popup/features.lua
lua/crates/src/common.lua
lua/crates/types.lua
lua/crates/util.lua
teal/crates/api.tl
teal/crates/core.tl
teal/crates/diagnostic.tl
teal/crates/popup/features.tl
teal/crates/src/common.tl
teal/crates/types.tl
teal/crates/util.tl

Improves #91 by speeding up the conversion from the `crates.io` json object to the interal representation

perf: significantly speed up feature parsing

---

doc/crates.txt
docgen/templates/documentation.md.in
docgen/wiki/Unstable-documentation.md
lua/crates/config.lua
lua/crates/init.lua
lua/crates/lsp.lua
lua/crates/null-ls.lua
lua/crates/src/cmp.lua
lua/crates/src/common.lua
lua/crates/util.lua
teal/crates/config.tl
teal/crates/init.tl
teal/crates/lsp.tl
teal/crates/null-ls.tl
teal/crates/src/cmp.tl
teal/crates/src/common.tl
teal/crates/util.tl
types/vim.d.tl

As mentioned in #78, this implements an in-process lsp server.
it can be enabled in the configuration:
```lua
require("crates").setup({
lsp = {
enable = true,
on_attach = function(client, buf) end,
}
})
```
`on_attach` can be the same function as passed to any other language servers.

feat: in-process lsp server

---

lua/crates/lsp.lua

Also setup an `on_exit` handler.
Without this change - when one opens a `Cargo.toml`, closes it and then re-opens it (or a different one in a workspace):
With this change:

Re-use an existing language server if already started.

---

docgen/shared/plain_text_config.lua
docgen/templates/documentation.md.in
lua/crates/api.lua
lua/crates/completion/cmp.lua
lua/crates/completion/common.lua
lua/crates/completion/coq.lua
lua/crates/config/init.lua
lua/crates/config/types.lua
lua/crates/core.lua
lua/crates/init.lua
lua/crates/lsp.lua
lua/crates/src/common.lua
lua/crates/state.lua
lua/crates/toml.lua
lua/crates/types.lua

It's not quite perfect just yet, but here's my 1-day implementation of crate name autocompletion as talked about in #115.
You can see it in action here
https://github.com/Saecki/crates.nvim/assets/91832471/e1af7ef2-dba3-4d27-a466-9e5fae562e2f

Implement crate name autocompletion

---

lua/crates/toml.lua

It seems i was right to worry about accidentally breaking something with that last minor change, neovim started freezing whenever i tried to type in an array table because I fucked up the logic of parsing the table headers. I've done it much more carefully this time, so that shouldn't happen anymore

Fix freeze when parsing array tables

---

docgen/templates/documentation.md.in
lua/crates/config/init.lua

closes #132
neoconf does most of the heavy lifting, just added an additional function when building the config to overlay any local settings gotten from neoconf

feat: neoconf integration

---

lua/crates/util.lua

This should make is so that using "start" as an open_program in the config actually works on windows. it changes the executable check out for an try-catch basically.

fix: Make command execution on windows work for non-exe open methods

---

lua/crates/time.lua

Relaxes the requirement of having an explicit timezone (`+HH:MM`) in the date string, and adds support for `Z` suffixes representing UTC.

fix: parsing of RFC 3339 dates without explicit timezone

---

lua/crates/api.lua
lua/crates/semver.lua

First, thanks for this plugin! It's very useful.
The last updated version is not necessarily the latest version. (e.g., the latest version of [usbd-hid](https://crates.io/crates/usbd-hid/versions) is currently 0.8.2, but was last updated to 0.7.1).
This creates a warning diagnosis to the wrong latest version.
To solve this problem, the fetched crate versions are now sorted by semver.

fix: sort fetched crate versions

---

lua/crates/toml.lua

fix: invalid dependency section warnings

---

lua/crates/diagnostic.lua
lua/crates/util.lua

When the user requests a pre-release (e.g. `crate = "1.0.0-alpha.3"`), an update diagnostic was shown to the user even if the requested pre-release was the newest release.
This makes sure that both `newest` and `newest_pre` are considered when checking if the newest found version is matched by the user's requirements.

fix: prevent update diagnostics from showing for matching pre-releases

---

doc/crates.txt
docgen/wiki/Documentation-unstable.md
lua/crates/config/init.lua
lua/crates/popup/common.lua

Replace the default value for `popup.border` with whatever the global `winborder` setting added in nvim 0.11 is. If the neovim version is less than 0.11, default to "none" instead as before.
Previously the `winborder` setting was ignored and there was no way to override it, since the config is automatically filled up with the configured default values. I considered setting the default to `nil` and modifying the window code like this:
```diff
-        border = state.cfg.popup.border,
+        border = state.cfg.popup.border or vim.opt_global.winborder:get() or "none",
```
but that will fall apart if the border setting is ever used in a second location (or the code above must be replicated). Also the chosen approach of overwriting the default has the nice side-effect that users that haven't …

feat: support nvim 0.11 winborder as popup.border

---

lua/crates/semver.lua

fix(semver): compare pre-release strings

---

doc/crates.txt
docgen/gen_doc.lua
docgen/templates/documentation.md.in
docgen/wiki/Documentation-unstable.md
lua/crates/config/init.lua
lua/crates/health.lua
scripts/gen_types.lua

This deprecates the completion engine specific sources, and the null-ls actions.
The in-process language server can be used instead.

feat!: deprecate the nvim-cmp, coq_nvim, and null-ls sources
